<?php
/**
 * Copyright © 2021 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/** @var \TNW\AuthorizeCim\Block\Customer\PaymentProfiles $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<div class="fieldset-wrapper" id="payment-profiles-info">
    <div class="fieldset-wrapper-content">
        <div class="manage-payment-method">
            <div class="ui-tabs">
                <ul class="address-list ui-tabs-nav">
                    <?php if ($block->isExistsPaymentProfiles()): ?>
                        <?php foreach ($block->getPaymentProfiles() as $profile): ?>
                            <?= $block->renderProfileHtml($profile); ?>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <?= $escaper->escapeHtml(__('There are currently no active payment profiles.')); ?>
                    <?php endif; ?>
                </ul>
                <div class="address-item-edit">
                    <div class="address-item-edit-content">
                        <?= $block->getChildHtml('customer.edit.tab.paymentinfo.card.form'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#payment-profiles-info": {
            "TNW_AuthorizeCim/js/paymentProfilesInfo": {}
        }
    }
</script>
<?= $block->getChildHtml('tnw_authorize_cim_payment_script') ?>
<?php
$scriptString = <<<script
require([
    'jquery'
], function ($) {
    $('body').trigger('contentUpdated');
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
