<?php
/**
 * Copyright © 2021 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/** @var \TNW\AuthorizeCim\Block\Customer\PaymentProfiles $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<div class="fieldset-wrapper" id="payment-profiles-info">
    <div class="fieldset-wrapper-content">
        <div class="manage-payment-method">
            <div class="ui-tabs">
                <?php if ($block->isExistsPaymentProfiles()): ?>
                    <ul class="address-list ui-tabs-nav">
                        <?php foreach ($block->getPaymentProfiles() as $profile): ?>
                            <?= $block->renderProfileHtml($profile); ?>
                        <?php endforeach; ?>
                    </ul>
                <?php else: ?>
                    <table>
                        <tr>
                            <td>
                                <div class="message info empty">
                                    <span>
                                        <?= $escaper->escapeHtml(__('There are currently no active payment profiles.')); ?>
                                    </span>
                                </div>
                            </td>
                        </tr>
                    </table>
                <?php endif; ?>
                <div class="address-item-edit">
                    <?= $block->getChildHtml('customer.edit.tab.paymentinfo.card.form'); ?>
                </div>
            </div>
        </div>
    </div>
    <?= $block->getChildHtml('tnw_authorize_cim_payment_script') ?>
    <?php
    $scriptString = <<<script
require([
    'jquery'
], function ($) {
    $('body').trigger('contentUpdated');
});
script;
    ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
</div>

<script type="text/x-magento-init">
    {
        "#payment-profiles-info": {
            "TNW_AuthorizeCim/js/paymentProfilesInfo": {}
        }
    }
</script>
