<?php
/**
 * Copyright © 2021 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/** @var \TNW\AuthorizeCim\Block\Payment $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$scriptString = <<<script
require([
        'jquery',
        'TNW_AuthorizeCim/js/customer/authorize',
        'domReady!'
    ], function($, Authorize) {
        var config = {$block->getPaymentConfig()},
            payment;
        payment = new Authorize(config);
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
