<?php
/**
 * Copyright © 2021 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/** @var \TNW\AuthorizeCim\Block\Form $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

$code = $escaper->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
?>
<fieldset class="fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>">
    <div class="fieldset-wrapper-title">
        <strong class="title">
            <span><?= $escaper->escapeHtml(__('Credit Card Information')) ?></span>
        </strong>
    </div>
    <div class="field-type field required">
        <label class="label" for="<?= /* @noEscape */ $code ?>_cc_type">
            <span><?= $escaper->escapeHtml(__('Credit Card Type')) ?></span>
        </label>
        <div class="field-control">
            <select name="payment[cc_type]"
                    id="<?= /* @noEscape */ $code ?>_cc_type"
                    class="required-entry validate-cc-type-select control-select">
                <option value=""></option>
                <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName): ?>
                    <option value="<?= $escaper->escapeHtml($typeCode) ?>" <?php if ($typeCode == $ccType): ?>selected="selected"<?php endif ?>>
                        <?= $escaper->escapeHtml($typeName) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="field-number field required">
        <label class="label" for="<?= /* @noEscape */ $code ?>_cc_number">
            <span><?= $escaper->escapeHtml(__('Credit Card Number')) ?></span>
        </label>
        <div class="field-control">
            <input type="text"
                   name="payment[cc_number]"
                   id="<?= /* @noEscape */ $code ?>_cc_number"
                   title="<?= $escaper->escapeHtml(__('Credit Card Number')) ?>"
                   class="control-text validate-cc-number"
                   value="<?= /* @noEscape */ $block->getInfoData('cc_number') ?>"/>
        </div>
    </div>
    <div class="field-date field required">
        <label class="label" for="<?= /* @noEscape */ $code ?>_expiration">
            <span><?= $escaper->escapeHtml(__('Expiration Date')) ?></span>
        </label>
        <div class="field-control">
            <select name="payment[cc_exp_month]"
                    id="<?= /* @noEscape */ $code ?>_expiration"
                    class="control-select control-select-month validate-cc-exp required-entry">
                <?php foreach ($block->getCcMonths() as $k => $v): ?>
                    <option value="<?= $escaper->escapeHtml($k) ?>"
                            <?php if ($k == $ccExpMonth): ?>selected="selected"<?php endif ?>>
                        <?= $escaper->escapeHtml($v) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <select name="payment[cc_exp_year]"
                    id="<?= /* @noEscape */ $code ?>_expiration_yr"
                    class="control-select control-select-year required-entry">
                <?php foreach ($block->getCcYears() as $k => $v): ?>
                    <option value="<?= /* @noEscape */ $k ? $escaper->escapeHtml($k) : '' ?>"
                            <?php if ($k == $ccExpYear): ?>selected="selected"<?php endif ?>>
                        <?= $escaper->escapeHtml($v) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <?php if ($block->hasVerification()): ?>
        <div class="field-number required field required">
            <label class="label" for="<?= /* @noEscape */ $code ?>_cc_cid">
                <span><?= $escaper->escapeHtml(__('Card Verification Number')) ?></span>
            </label>
            <div class="field-control">
                <input type="text"
                       name="payment[cc_cid]"
                       id="<?= /* @noEscape */ $code ?>_cc_cid"
                       title="<?= $escaper->escapeHtml(__('Card Verification Number')) ?>"
                       class="required-entry validate-cc-cvn control-cvn control-text"
                       value="<?= /* @noEscape */ $block->getInfoData('cc_cid') ?>"/>
            </div>
        </div>
    <?php endif; ?>

    <input type="hidden" id="<?= /* @noEscape */ $code ?>_opaque_descriptor"
           name="payment[opaqueDescriptor]"/>
    <input type="hidden" id="<?= /* @noEscape */ $code ?>_opaque_value"
           name="payment[opaqueValue]"/>
</fieldset>
