<?php
/**
 * Copyright © 2021 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

/** @var \TNW\AuthorizeCim\Block\Adminhtml\Customer\CreditCard\Form $block */
/** @var \Magento\Customer\Block\DataProviders\AddressAttributeData $customerAddressAttributeData */
/** @var \Magento\Customer\Block\DataProviders\PostCodesPatternsAttributeData $customerPostCodesPatternsAttributeData */
/** @var \Magento\Directory\Block\Data $directoryData */
/** @var \Magento\Customer\ViewModel\Address $customerAddressViewModel */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
$customerAddressAttributeData = $block->getCustomerAddressAttributeData();
$customerPostCodesPatternsAttributeData = $block->getCustomerPostCodesPatternsAttributeData();
$directoryData = $block->getDirectoryData();
$customerAddressViewModel = $block->getCustomerAddressViewModel();
$code = $block->getCurrentMethod()->getCode();
?>

<?php $_firstname = $customerAddressAttributeData->getFrontendLabel('firstname'); ?>
<?php $_lastname = $customerAddressAttributeData->getFrontendLabel('lastname'); ?>
<?php $_company = $customerAddressAttributeData->getFrontendLabel('company'); ?>
<?php $_telephone = $customerAddressAttributeData->getFrontendLabel('telephone'); ?>
<?php $_street = $customerAddressAttributeData->getFrontendLabel('street'); ?>
<?php $_country_id = $customerAddressAttributeData->getFrontendLabel('country_id'); ?>
<?php $_region = $customerAddressAttributeData->getFrontendLabel('region'); ?>
<?php $_city = $customerAddressAttributeData->getFrontendLabel('city'); ?>
<?php $_postcode = $customerAddressAttributeData->getFrontendLabel('postcode'); ?>
<?php $_selectRegion = 'Please select a region, state or province.'; ?>
<?php $_displayAll = $block->getConfig('general/region/display_all'); ?>

<?php $_firstnameValidationClass = $customerAddressViewModel->addressGetAttributeValidationClass('firstname'); ?>
<?php $_lastnameValidationClass = $customerAddressViewModel->addressGetAttributeValidationClass('lastname'); ?>
<?php $_companyValidationClass = $customerAddressViewModel->addressGetAttributeValidationClass('company'); ?>
<?php $_telephoneValidationClass = $customerAddressViewModel->addressGetAttributeValidationClass('telephone'); ?>
<?php $_streetValidationClass = $customerAddressViewModel->addressGetAttributeValidationClass('street'); ?>
<?php $_streetValidationClassNotRequired = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
<?php $_regionValidationClass = $customerAddressViewModel->addressGetAttributeValidationClass('region'); ?>
<?php $_cityValidationClass = $customerAddressViewModel->addressGetAttributeValidationClass('city'); ?>
<?php $_postcodeValidationClass = $customerAddressViewModel->addressGetAttributeValidationClass('postcode'); ?>

<div class="block-title">
    <h2><?= $escaper->escapeHtml(__('Add A Credit Card')); ?></h2>
    <form class="customer-payment-profile"
          action="<?= $escaper->escapeUrl($block->getSaveUrl()) ?>"
          method="post"
          id="<?= $code; ?>-form-validate"
          enctype="multipart/form-data"
          data-mage-init='{"validation": {}}'
          data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
        <?= $block->getBlockHtml('formkey'); ?>
        <input type="hidden" name="method" value="<?= $code; ?>"/>
        <fieldset class="admin__fieldset">
            <div class="admin__fieldset-wrapper-title">
                <strong class="title">
                    <span><?= $escaper->escapeHtml(__('Cardholder Information')) ?></span>
                </strong>
            </div>
            <div class="admin__field field-name-firstname _required">
                <label class="admin__field-label" for="<?= $code; ?>-firstname">
                    <span><?= /* @noEscape */ $_firstname; ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="billing[firstname]"
                           id="<?= $code; ?>-firstname"
                           title="<?= /* @noEscape */ $_firstname; ?>"
                           value=""
                           class="admin__control-text input-text <?= $escaper->escapeHtmlAttr($_firstnameValidationClass); ?>"/>
                </div>
            </div>
            <div class="admin__field field-name-lastname _required">
                <label class="admin__field-label" for="<?= $code; ?>-lastname">
                    <span><?= /* @noEscape */ $_lastname; ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="billing[lastname]"
                           id="<?= $code; ?>-lastname"
                           title="<?= /* @noEscape */ $_lastname; ?>"
                           value=""
                           class="admin__control-text input-text <?= $escaper->escapeHtmlAttr($_lastnameValidationClass); ?>"/>
                </div>
            </div>
            <div class="admin__field company">
                <label class="admin__field-label" for="<?= $code; ?>-company">
                    <span><?= /* @noEscape */ $_company; ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="billing[company]"
                           id="<?= $code; ?>-company"
                           title="<?= /* @noEscape */ $_company; ?>"
                           value=""
                           class="admin__control-text input-text <?= $escaper->escapeHtmlAttr($_companyValidationClass); ?>"/>
                </div>
            </div>
            <div class="admin__field telephone <?php if (strpos($_telephoneValidationClass, 'required') !== false) : ?>_required<?php endif; ?>">
                <label class="admin__field-label" for="<?= $code; ?>-telephone">
                    <span><?= /* @noEscape */ $_telephone; ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="billing[telephone]"
                           id="<?= $code; ?>-telephone"
                           value=""
                           title="<?= /* @noEscape */ $_telephone; ?>"
                           class="admin__control-text input-text <?= $escaper->escapeHtmlAttr($_telephoneValidationClass); ?>"/>
                </div>
            </div>
        </fieldset>
        <fieldset class="admin__fieldset">
            <div class="admin__fieldset-wrapper-title">
                <strong class="title">
                    <span><?= $escaper->escapeHtml(__('Cardholder Address')) ?></span>
                </strong>
            </div>
            <div class="admin__field street _required">
                <label for="<?= $code; ?>-street_1" class="admin__field-label">
                    <span><?= /* @noEscape */ $_street; ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="billing[street][]"
                           id="<?= $code; ?>-street_1"
                           value=""
                           title="<?= /* @noEscape */ $_street; ?>"
                           class="admin__control-text input-text <?= $escaper->escapeHtmlAttr($_streetValidationClass); ?>"/>
                    <div class="nested">
                        <?php for ($_i = 1, $_n = $customerAddressViewModel->addressGetStreetLines(); $_i < $_n; $_i++): ?>
                            <div class="admin__field additional">
                                <label class="admin__field-label" for="street_<?= /* @noEscape */ $_i + 1 ?>">
                                    <span><?= $escaper->escapeHtml(__('Street Address: Line %1', $_i + 1)) ?></span>
                                </label>
                                <div class="admin__field-control">
                                    <input type="text"
                                           name="billing[street][]"
                                           id="<?= $code; ?>street_<?= /* @noEscape */ $_i + 1 ?>"
                                           value=""
                                           title="<?= $escaper->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                           class="admin__control-text input-text <?= $escaper->escapeHtmlAttr($_streetValidationClassNotRequired); ?>"/>
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>
            <div class="admin__field country _required">
                <label class="admin__field-label" for="<?= $code; ?>-country">
                    <span><?= /* @noEscape */ $_country_id; ?></span>
                </label>
                <div class="admin__field-control">
                    <?= str_replace('class="', 'class="admin__control-select ', $directoryData->getCountryHtmlSelect(null, 'billing[country_id]', $code . '-country')) ?>
                </div>
            </div>
            <div class="admin__field region _required">
                <label class="admin__field-label" for="<?= $code; ?>-region-id">
                    <span><?= /* @noEscape */ $_region ?></span>
                </label>
                <div class="admin__field-control">
                    <select name="billing[region_id]"
                            id="<?= $code; ?>-region-id"
                            title="<?= /* @noEscape */ $_region ?>"
                            class="admin__control-select validate-select"
                            <?= /* @noEscape */ !$_displayAll ? ' disabled="disabled"' : '' ?>>
                        <option value=""><?= $escaper->escapeHtml(__($_selectRegion)) ?></option>
                    </select>
                    <input type="text"
                           name="billing[region]"
                           id="<?= $code; ?>-region"
                           value=""
                           title="<?= /* @noEscape */ $_region ?>"
                           class="admin__control-text input-text <?= $escaper->escapeHtmlAttr($_regionValidationClass) ?>"
                           <?= !$_displayAll ? ' disabled="disabled"' : '' ?>/>
                </div>
            </div>
            <div class="admin__field city _required">
                <label class="admin__field-label" for="<?= $code; ?>-city">
                    <span><?= /* @noEscape */ $_city; ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="billing[city]"
                           id="<?= $code; ?>-city"
                           value=""
                           title="<?= /* @noEscape */ $_city; ?>"
                           class="admin__control-text input-text <?= $escaper->escapeHtmlAttr($_cityValidationClass); ?>"/>
                </div>
            </div>
            <div class="admin__field zip _required">
                <label class="admin__field-label" for="<?= $code; ?>-zip">
                    <span><?= /* @noEscape */ $_postcode; ?></span>
                </label>
                <div class="admin__field-control">
                    <input type="text"
                           name="billing[postcode]"
                           id="<?= $code; ?>-zip"
                           value=""
                           title="<?= /* @noEscape */ $_postcode; ?>"
                           class="admin__control-text input-text validate-zip-international <?= $escaper->escapeHtmlAttr($_postcodeValidationClass); ?>"/>
                    <div role="alert" class="message warning">
                        <span></span>
                    </div>
                    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag("display: none;", 'div.message.warning') ?>
                </div>
            </div>
        </fieldset>
        <?= $block->getMethodFormBlockHtml(); ?>
        <div class="actions-toolbar">
            <button type="submit"
                    class="action-save primary"
                    data-action="save-address"
                    title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $escaper->escapeHtml(__('Save')) ?></span>
            </button>
            <button type="reset"
                    class="action secondary"
                    form="<?= $code; ?>-form-validate">
                <span><?= $escaper->escapeHtml(__('Cancel')) ?></span>
            </button>
        </div>
    </form>
</div>
<?php
$countryId = "{$code}-country";
$regionInputId = "{$code}-region";
$regionListId = "{$code}-region-id";
$regionJson = $customerAddressViewModel->dataGetRegionJson();
$scriptString = <<<script
require([
    "jquery",
    "mage/adminhtml/form"
], function(jQuery){
    var updater = new RegionUpdater(
        '{$countryId}',
        '{$regionInputId}',
        '{$regionListId}',
        {$regionJson},
        'disable'
    );
    window.updater = updater;
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
