<?php
/**
 * Copyright © 2021 TechNWeb, Inc. All rights reserved.
 * See TNW_LICENSE.txt for license details.
 */

use Magento\Vault\Api\Data\PaymentTokenInterface;

/** @var \TNW\AuthorizeCim\Block\Adminhtml\Customer\CreditCard\Renderer $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<li class="address-list-item<?php if ($block->getToken()->getExpiresAt() != '' && strtotime($block->getToken()->getExpiresAt()) < time()): ?> expired<?php endif; ?>">
    <div class="address-list-item-actions">
        <?php if (!true): ?>
            <abbr title="<?= $escaper->escapeHtmlAttr(__('This payment record cannot be modified while associated with pending orders.')); ?>"><?php echo $escaper->escapeHtml(__('Card In Use')); ?></abbr>
        <?php else: ?>
            <form class="form"
                  action="<?= $escaper->escapeUrl($block->getUrl('customer/paymentProfiles/delete', ['_current' => true])) ?>"
                  method="post"
                  enctype="multipart/form-data"
            >
                <?= $block->getBlockHtml('formkey') ?>
                <input
                    name="<?= /* @noEscape */ PaymentTokenInterface::PUBLIC_HASH ?>"
                    value="<?= /* @noEscape */ $block->getToken()->getPublicHash() ?>"
                    type="hidden"/>
                <button class="action-delete danger-zone" type="submit">
                    <span><?php echo $escaper->escapeHtml(__('Delete')) ?></span>
                </button>
            </form>
        <?php endif; ?>
    </div>
    <address>
        <div class="cc-image">
            <?php if (!empty($block->getToken()->getType())): ?>
                <img src="<?= /* @noEscape */ $block->getIconUrl() ?>"
                     width="<?= /* @noEscape */ $block->getIconWidth() ?>"
                     height="<?= /* @noEscape */ $block->getIconHeight() ?>"
                >
            <?php endif; ?>
        </div>
        <div class="additional-data">
            <span><?= $escaper->escapeHtml($block->getNumberLast4Digits()); ?></span>
            <?php if ($block->getExpDate() != ''): ?>
                <small><?php echo $escaper->escapeHtml(__('(Expires %1)', $block->getExpDate())); ?></small>
            <?php endif; ?>
        </div>
    </address>
</li>
